### ISSUE TITLE
cctalk implementation

### ISSUE THREAD

**Issue by dennissaenz** [vltgroup/ccTalk#1]
Hi, im wondering if you have an example of an implementation of your cctalk.
in your README.md : to start: instantiate com.vltgroup.ccTalk.bus.Bus over you com.vltgroup.ccTalk.comport.ComPort implementation

static byte[] BNVCode = null;
static comPort port="_COM3_";
Bus bus = new Bus(port, BNVCode);

regards!

**Comment by vltgroup** [comment]
add workable example for PC platform
