### ISSUE TITLE
Doesn't detect AST GBA_ST1

### ISSUE THREAD

**Issue by nitramb** [vltgroup/ccTalk#2]
This is the output I get:

--- exec-maven-plugin:1.2.1:exec (default-cli) @ examplePC ---
Picked up _JAVA_OPTIONS: -Xmx512M
2019-05-19 04:16:43,831 INFO  com.vltgroup.ccTalk.bus.Bus.<init>:49 scan CRC8:
2019-05-19 04:16:45,437 INFO  com.vltgroup.ccTalk.bus.Bus.<init>:55 scan CRC16:
2019-05-19 04:16:47,039 INFO  com.vltgroup.ccTalk.bus.Bus.<init>:61 scan ENCRYPTED:
2019-05-19 04:16:48,641 INFO  com.vltgroup.ccTalk.bus.Bus.<init>:68 scan FINISHED

Now I know you are sending the correct data because when I compared it with a working app I have in C# the bytes sent are the same and you are using the same serial parameters and flowcontrolmode that is used in the other app . The issue seems to be with the serialEvents it doesn't ever receive any.

AST GBA_ST1 uses CRC16bit for the checksum.

If you need any extra information please just ask.

Nitram

**Comment by vltgroup** [comment]
You mean Bill Acceptor GBA ST1 ? never use it
library use slf4j for logging, if you enable DEBUG log level  - you will see binary log - copy it here
and uncomment debug logs in examplePC\src\main\java\com\vltgroup\ccTalk\examplePC\ComPort.java

**Comment by goblooge** [comment]
same here. i also got same problem with NV 9+ Bill Acceptor. seem it doesnt log got anything or gave anything. just silence. and the bill acceptor light also not on.

Scanning for projects...
                                                                        
------------------------------------------------------------------------
Building examplePC 1.0-SNAPSHOT
------------------------------------------------------------------------

--- maven-dependency-plugin:2.1:copy-dependencies (default) @ examplePC ---
Copying logback-classic-1.1.7.jar to C:\Users\Administrador\Documents\ccTalk\examplePC\target\lib\logback-classic-1.1.7.jar
Copying logback-core-1.1.7.jar to C:\Users\Administrador\Documents\ccTalk\examplePC\target\lib\logback-core-1.1.7.jar
Copying ccTalk-1.0-SNAPSHOT.jar to C:\Users\Administrador\Documents\ccTalk\examplePC\target\lib\ccTalk-1.0-SNAPSHOT.jar
Copying jssc-2.8.0.jar to C:\Users\Administrador\Documents\ccTalk\examplePC\target\lib\jssc-2.8.0.jar
Copying slf4j-api-1.7.7.jar to C:\Users\Administrador\Documents\ccTalk\examplePC\target\lib\slf4j-api-1.7.7.jar

--- maven-resources-plugin:2.5:resources (default-resources) @ examplePC ---
[debug] execute contextualize
Using 'UTF-8' encoding to copy filtered resources.
skip non existing resourceDirectory C:\Users\Administrador\Documents\ccTalk\examplePC\src\main\resources

--- maven-compiler-plugin:2.3.2:compile (default-compile) @ examplePC ---
Compiling 3 source files to C:\Users\Administrador\Documents\ccTalk\examplePC\target\classes

--- exec-maven-plugin:1.2.1:exec (default-cli) @ examplePC ---
2019-08-28 11:34:16,924 INFO  com.vltgroup.ccTalk.bus.Bus.<init>:49 scan CRC8:
2019-08-28 11:34:18,617 INFO  com.vltgroup.ccTalk.bus.Bus.<init>:55 scan CRC16:
2019-08-28 11:34:20,301 INFO  com.vltgroup.ccTalk.bus.Bus.<init>:61 scan ENCRYPTED:
2019-08-28 11:34:21,923 INFO  com.vltgroup.ccTalk.bus.Bus.<init>:68 scan FINISHED

**Comment by aleshchik** [comment]
Check the firmware of your devices. I had the same problems. It turned out the problem was in the wrong protocol in the device settings.

**Comment by goblooge** [comment]
oh... okay let me take a look

**Comment by aleshchik** [comment]
I can't tell you the exact version i've chosen, i helped my mate with the payment devices 6 months ago.
Also i had a problems with bad usb cable(device was not visible at all) and permissions to access the ports, but i've used linux.

**Comment by goblooge** [comment]
found it... and yes. you were right its the protocol. btw any example how can i stop the system. so i can make stop or start button. apparently close the bus sometime did not stop the machine.

**Comment by vltgroup** [comment]
ccTalk device can't be paused - it must be always polled, it polling stops device going to error state.
You can call Bus.close() - all polling will stops.
